const cupData = [
  {
    title: "[트위그뉴욕] 아멜리에 ZP 커피 골드",
    price: 53200,
    category: "mug",
    imgSrc: "/imgs/mug0.jpg",
    param: "mug0",
    status: "new",
  },
  {
    title: "[트위그뉴욕] 아멜리에 ZP 커피 블루",
    price: 53200,
    category: "mug",
    imgSrc: "/imgs/mug1.jpg",
    param: "mug1",
    status: "new",
  },
  {
    title: "[트위그뉴욕] 아멜리에 ZP 커피 핑크",
    price: 53200,
    category: "mug",
    imgSrc: "/imgs/mug2.jpg",
    param: "mug2",
    status: "new",
  },
  {
    title: "[트위그뉴욕] 아멜리에 ZP 커피 그린",
    price: 53200,
    category: "mug",
    imgSrc: "/imgs/mug3.jpg",
    param: "mug3",
    status: "new",
  },
  {
    title: "[쓰리코] 일자 컵",
    price: 40000,
    category: "tea",
    imgSrc: "/imgs/tea0.jpg",
    param: "tea0",
  },
  {
    title: "[쓰리코] 씨버드 티컵",
    price: 20000,
    category: "tea",
    imgSrc: "/imgs/tea1.jpg",
    param: "tea1",
  },
  {
    title: "[쓰리코] 씨버드 크리머",
    price: 50000,
    category: "tea",
    imgSrc: "/imgs/tea2.jpg",
    param: "tea2",
  },
  {
    title: "[메종필리아] 화이트 티팟 (700ml)",
    price: 85000,
    category: "tea",
    imgSrc: "/imgs/tea3.jpg",
    param: "tea3",
  },
  {
    title: "[메종필리아] 로즈 크리스탈 머그",
    price: 49900,
    category: "tea",
    imgSrc: "/imgs/tea4.jpg",
    param: "tea4",
  },
  {
    title: "[브라운즈] 원기둥 도자기 미니 찻잔",
    price: 15000,
    category: "tea",
    imgSrc: "/imgs/tea5.jpg",
    param: "tea5",
  },
  {
    title: "[브라운즈] 덤벙 도자기 쾌객배 세트",
    price: 114000,
    category: "tea",
    imgSrc: "/imgs/tea6.jpg",
    param: "tea6",
  },
  {
    title: "[서울번드 코워크] 모와니 글라스 버블 비즈 글라스 (5 colors)",
    price: 88000,
    category: "glass",
    imgSrc: "/imgs/glass0.jpg",
    param: "glass0",
  },
  {
    title: "[모도리] 유리컵 & 오프너세트",
    price: 39900,
    category: "glass",
    imgSrc: "/imgs/glass1.jpg",
    param: "glass1",
  },
  {
    title: "[모와니 글라스] 물방울 디저트 볼 S",
    price: 62000,
    category: "glass",
    imgSrc: "/imgs/glass2.jpg",
    param: "glass2",
  },
  {
    title: "[모와니 글라스] 물방울 글라스",
    price: 64000,
    category: "glass",
    imgSrc: "/imgs/glass3.jpg",
    param: "glass3",
  },
  {
    title: "[메종필리아] 에스텔 골드 쿠페 글라스 세트 (2pcs)",
    price: 120000,
    category: "glass",
    imgSrc: "/imgs/glass4.jpg",
    param: "glass4",
  },
  {
    title: "[메종필리아] 로즈 크리스탈 와인 글라스 세트 (2pcs)",
    price: 120000,
    category: "glass",
    imgSrc: "/imgs/glass5.jpg",
    param: "glass5",
  },
  {
    title: "[메종필리아] 로즈 크리스탈 텀블러 세트 (2pcs)",
    price: 88000,
    category: "glass",
    imgSrc: "/imgs/glass6.jpg",
    param: "glass6",
  },
  {
    title: "[박선민] 리:엔티크 플랫잔 세트 (그린)",
    price: 76000,
    category: "mug",
    imgSrc: "/imgs/mug4.jpg",
    param: "mug4",
  },
  {
    title: "[박선민] 리:엔티크 플랫잔 세트 (브라운)",
    price: 76000,
    category: "mug",
    imgSrc: "/imgs/mug5.jpg",
    param: "mug5",
  },
  {
    title: "[박선민] 리:엔티크 플랫잔 세트 여름 한정판",
    price: 72000,
    category: "mug",
    imgSrc: "/imgs/mug6.jpg",
    param: "mug6",
  },
  {
    title: "[소나이트] 벼껍질 업사이클링 티 트레이 M (2 colors)",
    price: 23000,
    category: "tea",
    imgSrc: "/imgs/tea7.jpg",
    param: "tea7",
  },
  {
    title: "[소나이트] 벼껍질 업사이클링 소품 보관함 세트 (2 colors)",
    price: 60000,
    category: "tea",
    imgSrc: "/imgs/tea8.jpg",
    param: "tea8",
  },
];

export default cupData;
