const data = [
  {
    title: "[트위그뉴욕] 마리 커피 1인 세트",
    price: 42000,
    category: "plate",
    imgSrc: "/imgs/plate0.jpg",
    status: "new",
    param: "plate0",
  },

  {
    title: "[트위그뉴욕] 마리 커피 2인 세트",
    price: 82000,
    category: "plate",
    imgSrc: "/imgs/plate1.jpg",
    status: "new",
    param: "plate1",
  },

  {
    title: "[트위그뉴욕] 마리 1인 티타임 세트",
    price: 74000,
    category: "plate",
    imgSrc: "/imgs/plate2.jpg",
    status: "new",
    param: "plate2",
  },

  {
    title: "[트위그뉴욕] 마리 티타임 세트",
    price: 148000,
    category: "plate",
    imgSrc: "/imgs/plate3.jpg",
    status: "new",
    param: "plate3",
  },
  {
    title: "[오덴세] 라고아 국공기 (3 colors)",
    price: 22000,
    category: "bowl",
    imgSrc: "/imgs/bowl0.jpg",
    param: "bowl0",
  },
  {
    title: "[오덴세] 라고아 면기 (3 colors)",
    price: 55000,
    category: "bowl",
    imgSrc: "/imgs/bowl1.jpg",
    param: "bowl1",
  },

  {
    title: "[오덴세] 라고아 미디움 원형접시 (3 colors)",
    price: 30000,
    category: "plate",
    imgSrc: "/imgs/plate4.jpg",
    param: "plate4",
  },
  {
    title: "[오덴세] 라고아 밥공기 (3 colors)",
    price: 20000,
    category: "bowl",
    imgSrc: "/imgs/bowl2.jpg",
    param: "bowl2",
  },
  {
    title: "[오덴세] 레고트 밥공기 (3 colors)",
    price: 20000,
    category: "bowl",
    imgSrc: "/imgs/bowl3.jpg",
    param: "bowl3",
  },
  {
    title: "[오덴세] 아틀리에노드 라지 원형접시 (2 colors)",
    price: 37000,
    category: "plate",
    imgSrc: "/imgs/plate5.jpg",
    param: "plate5",
  },
  {
    title: "[다문] 문스톤 밥그릇",
    price: 230000,
    category: "bowl",
    imgSrc: "/imgs/bowl4.jpg",
    param: "bowl4",
  },
  {
    title: "[거창유기] 연공기",
    price: 54000,
    category: "bowl",
    imgSrc: "/imgs/bowl5.jpg",
    param: "bowl5",
    status: "best",
  },
  {
    title: "[거창유기] 평공기",
    price: 58000,
    category: "bowl",
    imgSrc: "/imgs/bowl6.jpg",
    param: "bowl6",
  },
  {
    title: "[지승민의공기] 와이 공기 (아이보리)",
    price: 25000,
    category: "bowl",
    imgSrc: "/imgs/bowl7.jpg",
    param: "bowl7",
    status: "best",
  },
  {
    title: "[크렘] 팔레트 테이블 매트 + 수저받침 세트 (화이트)",
    price: 67000,
    category: "mat",
    imgSrc: "/imgs/mat0.jpg",
    param: "mat0",
  },
  {
    title: "[크렘] 팔레트 테이블 매트 + 수저받침 세트 (아이스 블루)",
    price: 67000,
    category: "mat",
    imgSrc: "/imgs/mat1.jpg",
    param: "mat1",
  },
  {
    title: "[크렘] 팔레트 테이블 매트 + 수저받침 세트 (사틴 핑크)",
    price: 67000,
    category: "mat",
    imgSrc: "/imgs/mat2.jpg",
    param: "mat2",
    status: "best",
  },
  {
    title: "[르엔미] 에그 가죽 트레이",
    price: 29000,
    category: "mat",
    imgSrc: "/imgs/mat3.jpg",
    param: "mat3",
  },
  {
    title: "[서울번드 화] 꼬또네 x 서울번드 (테이블매트)",
    price: 29000,
    category: "mat",
    imgSrc: "/imgs/mat4.jpg",
    param: "mat4",
  },
  {
    title: "[서울번드 화] 꼬또네 x 서울번드 (러너)",
    price: 53000,
    category: "mat",
    imgSrc: "/imgs/mat5.jpg",
    param: "mat5",
  },
  {
    title: "[세라믹몽] 백자 비정형 꽃받침 (2 size)",
    price: 8000,
    category: "smallbowl",
    imgSrc: "/imgs/smallbowl0.jpg",
    param: "smallbowl0",
  },
  {
    title: "[세라믹몽] 백자 30각 찬기",
    price: 28000,
    category: "smallbowl",
    imgSrc: "/imgs/smallbowl1.jpg",
    param: "smallbowl1",
  },
  {
    title: "[세라믹몽] 청화 타원 수저받침",
    price: 12000,
    category: "smallbowl",
    imgSrc: "/imgs/smallbowl2.jpg",
    param: "smallbowl2",
  },
  {
    title: "[서울번드 코워크] 고요 찬기 (4 Type)",
    price: 41250,
    category: "smallbowl",
    imgSrc: "/imgs/smallbowl3.jpg",
    param: "smallbowl3",
  },
  {
    title: "[트위그뉴욕] 데이지체인 찬기 (L)",
    price: 26000,
    category: "smallbowl",
    imgSrc: "/imgs/smallbowl4.jpg",
    param: "smallbowl4",
  },
  {
    title: "[트위그뉴욕] 데이지체인 찬기 (M)",
    price: 22400,
    category: "smallbowl",
    imgSrc: "/imgs/smallbowl5.jpg",
    param: "smallbowl5",
  },
  {
    title: "[트위그뉴욕] 데이지체인 찬기 (S)",
    price: 17600,
    category: "smallbowl",
    imgSrc: "/imgs/smallbowl6.jpg",
    param: "smallbowl6",
    status: "best",
  },
  {
    title: "[아소토] 디저트 플레이트",
    price: 52000,
    category: "plate",
    imgSrc: "/imgs/plate6.jpg",
    param: "plate6",
  },
  {
    title: "[소나이트] 벼껍질 업사이클링 캡슐 트레이 S (4 colors)",
    price: 15000,
    category: "plate",
    imgSrc: "/imgs/plate7.jpg",
    param: "plate7",
  },
  {
    title: "[소나이트] 벼껍질 업사이클링 오벌 트레이 (2 colors)",
    price: 22000,
    category: "plate",
    imgSrc: "/imgs/plate8.jpg",
    param: "plate8",
  },
];

export default data;
